//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hacker_Document
    {
        public int Document_ID { get; set; }
        public string Document { get; set; }
        public string Document_Name { get; set; }
    }
}
