//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hacker_Registration
    {
        public int Registration_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Nic { get; set; }
        public Nullable<int> Batch_ID { get; set; }
        public Nullable<int> Course_ID { get; set; }
        public Nullable<int> Tel { get; set; }
    
        public virtual Hacker_Batch Hacker_Batch { get; set; }
        public virtual Hacker_Course Hacker_Course { get; set; }
    }
}
