//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LEARNINGEntities : DbContext
    {
        public LEARNINGEntities()
            : base("name=LEARNINGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hacker_Batch> Hacker_Batch { get; set; }
        public virtual DbSet<Hacker_Course> Hacker_Course { get; set; }
        public virtual DbSet<Hacker_Registration> Hacker_Registration { get; set; }
        public virtual DbSet<Hacker_User> Hacker_User { get; set; }
    }
}
